welshpaul_sitemap_sitemapindex:
    path: /sitemap/sitemap.xml
    defaults: { _controller: welshpaul.sitemap.sitemap:index }
welshpaul_sitemap_current:
    path: /sitemap/current.xml
    defaults: { _controller: welshpaul.sitemap.sitemap:current }
welshpaul_sitemap_topics:
    path: /sitemap/topics-{id}.xml
    defaults: { _controller: welshpaul.sitemap.sitemap:topics }
welshpaul_sitemap_forums:
    path: /sitemap/forums-{id}.xml
    defaults: { _controller: welshpaul.sitemap.sitemap:forums }
welshpaul_sitemap_additional:
    path: /sitemap/additional.xml
    defaults: { _controller: welshpaul.sitemap.sitemap:additional }
