welshpaul_sitemap_sitemapindex:
    pattern: /sitemap.xml
    defaults: { _controller: welshpaul.sitemap.sitemap:index }
welshpaul_sitemap_current:
    pattern: /current.xml
    defaults: { _controller: welshpaul.sitemap.sitemap:current }
welshpaul_sitemap_topics:
    pattern: /topics-{id}.xml
    defaults: { _controller: welshpaul.sitemap.sitemap:topics }
welshpaul_sitemap_forums:
    pattern: /forums-{id}.xml
    defaults: { _controller: welshpaul.sitemap.sitemap:forums }
