services:
    welshpaul.sitemap.sitemap:
        class: welshpaul\sitemap\controller\sitemap
        arguments:
            - '@auth'
            - '@cache'
            - '@config'
            - '@dbal.conn'
            - '@controller.helper'
            - '@dispatcher'
            - '%core.php_ext%'
            - '@ext.manager'
    welshpaul.sitemap.listener:
        class: welshpaul\sitemap\event\listener
        arguments:
            - '@config'
            - '@template'
            - '@user'
        tags:
            - { name: event.listener }
